### PR TITLE
Add pause method

### PR DESCRIPTION
**Pull request by akhromieiev**
The pause method is missed

### CODE REVIEW

**Comment by akhromieiev** [comment]
Could we merge this please?

**Comment by akhromieiev** [comment]
Sorry for disturbing @bazuka5801, but this is important part and would be good to merge this.

**Comment by riderx** [comment]
Agree !

**Review by bazuka5801 — APPROVED** [review]
🧐👍

**Comment by bazuka5801** [comment]
Available on `^3.0.1` version 🥳

**Pull request merged**
