### PR TITLE
NativeAudioWeb implementation

### PR DESCRIPTION
**Pull request by WhippyM**
belonging https://github.com/capacitor-community/native-audio/issues/2

Browser-Support: https://developer.mozilla.org/en-US/docs/Web/API/HTMLAudioElement#browser_compatibility

### CODE REVIEW

**Comment by riderx** [comment]
Wow thanks for that one !

**Review by riderx — APPROVED** [review]

**Comment by WhippyM** [comment]
@riderx you're welcome :relaxed: 
Hopefully matching the needs.

**Comment by riderx** [comment]
if you have to check that one @bazuka5801

**Comment by riderx** [comment]
@WhippyM i added your work to my fork and published it there: `npm i @forgr/native-audio`

**Comment by WhippyM** [comment]
Don't know why it's not getting merged. If there's something missing please let me know. @bazuka5801

**Pull request merged**
