### PR TITLE
fix: deprecated warning

### PR DESCRIPTION
**Pull request by riderx**
use new methods for capacitor plugin instead of depreacted one, it doesn't change the behaviors
`. success` to `.resolve`

### CODE REVIEW

**Comment by riderx** [comment]
@bazuka5801 super easy to merge :)

**Comment by riderx** [comment]
@bazuka5801 can we do something to help you  ?

**Comment by riderx** [comment]
@thomasvidas maybe you could help on this one ?

**Comment by bazuka5801** [comment]
@riderx Merged, will be available on `3.0.2`

**Comment by riderx** [comment]
@bazuka5801 thanks !

**Pull request merged**
