### PR TITLE
Fix stops the background music (updated)

### PR DESCRIPTION
**Pull request by riderx**
Fix this issue https://github.com/capacitor-community/native-audio/issues/40

This fix has been published on NPM until it's merged:
`npm i @forgr/native-audio`

By default, audio is not mixed on android and iOS, if you need to mix it just do :
```javascript
NativeAudio.configure({focus: false});
```

### For playback:
By default, using this category implies that your app’s audio is nonmixable—activating your session will interrupt any other audio sessions which are also nonmixable.
https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616509-playback

### For ambient:
When you use this category, audio from other apps mixes with your audio.
https://developer.apple.com/documentation/avfaudio/avaudiosession/category/1616560-ambient

## PS: 
this is a rework of the PR https://github.com/capacitor-community/native-audio/pull/42 but where the old behaviour is maintained.

### CODE REVIEW

**Comment by riderx** [comment]
@bazuka5801 if you can have a look ?

**Comment by benmarsh** [comment]
Would be great to get this merged in if all looks OK? I have an issue at the moment (in that the app steals focus when I boot it) and it appears this PR would fix that.

**Comment by riderx** [comment]
@bazuka5801 my fork is used in production since 2 month without issue i think it's safe to merge :)

**Comment by katche70** [comment]
Hi, could you please merge it into official master ?

**Comment by bazuka5801** [comment]
@riderx Thanks for contributing :100: 
Sorry for the long reply, I needed to make sure everything was working properly.

**Comment by riderx** [comment]
Thanks, i totally understand !

**Pull request merged**
