### PR TITLE
feat!: update to Capacitor v4

### PR DESCRIPTION
**Pull request by rdlabo**
By using `next` tag, This plugin can try to test on Capacitor 4.

```
% npm install @capacitor-community/native-audio@next
```

https://github.com/capacitor-community/native-audio/releases/tag/v4.0.0-0

However, this update was done automatically by `@rdlabo/capacitor-plugin-to-v4 ` ,and has not been confirmed to work. 

https://github.com/rdlabo-team/capacitor-plugin-to-v4

If you have any problems using it, please comment on this thread.

@maintainer Released with next tag to make the world compatible with Capacitor v4. Please check out this pull request and decide if you want to merge or not. Thanks for all your great work, and we look forward to working with you in the future.

### CODE REVIEW

**Comment by riderx** [comment]
@rdlabo seems the docgen is getting less info than before could you update to latest docgen and try again ?

**Comment by riderx** [comment]
Any news on that ?

**Comment by philkonick** [comment]
Any updates on this PR? At the moment I need to --force every npm install because of the dependency error.

**Comment by riderx** [comment]
i made this change here : https://github.com/Cap-go/native-audio

**Comment by facusatoshi** [comment]
HI! I tested today your version and its not playing audio. (no errors but either sound)
image

**Pull request merged**
